### ISSUE TITLE
Do something intelligent with metadata now.... `View Layer Meta Data`

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#209]
In #206, @KellyMWhitehead made sure we are bringing across our layer metadata AND our project metadata with each layer. @philipbaileynar said:

> Make sure it is stored as JSON so that we can do intelligent things with it later when the layer is promoted to a DCE layer.

My question is are we doing any of those "intelligent things" yet? Instead of waiting until "later when the layer is promoted to a DCE layer.", if what is happening is these are sitting there in context, we already have a `View Layer MetaData` right click command for every layer in QRV. Could we start doing something intelligent @philipbaileynar and @KellyMWhitehead by adding this right now to every layer node in tree?

![image](https://user-images.githubusercontent.com/9723905/230899605-40956977-2133-4394-9d80-e691fba4b703.png)

@philipbaileynar I know you will cringe at some of this...  It is trying to force us to connect the dots. Things that are more difficult we can set as lower priority (e.g. 1.0 milestone or later) and/or debate. I would set some basic functionality as a 0.3 or 0.4 priority.

## Add the Command
Right now, every node in the tree that is a layer has an `Edit` right click context menu command. 
![image](https://user-images.githubusercontent.com/9723905/230900221-bd5b7e37-5ad4-4a73-bd53-7565caba422c.png)

I'm asking to add to everyone (not just the context layers) a `View Layer Meta Data` context menu command. This will be a little different than above, because we have both Project Metadata and Layer Metadata. So it is not as simple as just a table control showing the layer metadata by key and values. Unlike in QRV tree, we don't have luxury of nested context of the project we're in to get back up to look at that project or its metadata.  So we will also need a form.

## View MetaData Form
In QRV, this currently is attempted to dock to panel by default. I think it makes more sense to float by default (and remember its state if possible if user moves it). 

- [ ] Add a section for the non-hidden Layer Metadata from json (include helpful copy commands by row)
![image](https://user-images.githubusercontent.com/9723905/230901016-916e83dc-de7b-454b-928a-2053c30c3a0b.png)
- [ ] Add button to view that layer in its original project
This will force Matt to implement the long-standing request for WebRV to have URLs save the layer specific view. Greyed out if layer is not from warehouse project (i.e. the projectURL is empty).
- [ ] Add a section for the non-hidden Project Metadata  (collapsed by default)
This will be greyed out and empty by default, except for layers either a) imported from QRV or b) layers included in an export to Warehouse (since the later can be done multiple times save only latest project URL). 
![image](https://user-images.githubusercontent.com/9723905/230901130-c7cf9d80-a218-4023-aceb-0e5551cfb589.png)
-[ ] Add a button offering to take user directly to that project (i.e. open riverscape project in warehouse by sending URL to default browser).
- [ ] Add new button for tables to export to *.csv
You have the copy to clipboards stuff... this is just going one step further and saving to text file.
- [ ] Add new button for tables to export to Google Sheets
This may be trickier but there are ways (e.g. [here](https://stackoverflow.com/questions/55026722/how-to-export-a-table-as-google-sheet-in-google-app-maker-using-a-button))
- [ ] Add ability to add MetaData keys and edit those added ones
I think we should be able to edit the custom added MetaData keys, but if a layer is imported from somwhere else, we should not be able to edit the "Source" metadata keys and values. 

## Update Edit Dialog
Finally, the edit menus in QRiS currently point to a lot of bespoke menus depending on the type (see #208).  Almost all of these look exactly like the original create forms. It is logical that users might also view the metadata from this "Inspect" location. 
- [ ] Add a button to those edit/inspect forms that brings up the updated floating `View Metadata` form. 
 
This would allow the closing and opening of the edit dialog and the metadata dialog to remain independent (i.e. you could switch focus between them (one is not always on top) and you don't have to exit one to view the other).

**Comment by joewheaton** [comment]
@philipbaileynar I am reassigning this to you so you and I discuss it and either park it or action it.

**Comment by joewheaton** [comment]
We are doing some intelligent things on importing metadata now. That's enough for the moment. For > 1.0, we will need to make specific tickets.
