### ISSUE TITLE
QRiS Design Tasks

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/QRiS#261]
NAR Tasks (@KellyMWhitehead)
- [x]  Add "As-Built" to design status 
 @joewheaton @nick4rivers we decided not to do this right?
That's right, we don't want this. We want "As-Built" to remain its own special type of DCE (needs specification in #268)
- [ ] Enable Layers tab on Design Form (same as DCE) (see #267)
- [x] Add new layers:
   - [x] Point Observations (Name, Notes/Description, Type_ID, Metadata)
   - [x] Line Observations (Name, Notes/Description, Type_ID, Metadata)
   - [x] Polygon Observations (Name, Notes/Description, Type_ID, Metadata)
- [x] Investigate Import Photos Tool for Point Observations (no development yet).
- [x] Investigate use of spatial views in QRiS
- [ ] #494
- [ ] #495

Anabranch Tasks (@nick4rivers, @Jdgilby)
 - [x] #267
 - [x] #268
- [x] QML/Symbology for layers  - see #265 
- [x] Define attributes for Layers - see #265 
   - [x] Observations Layers
   - [x] Structures Phase
   - [x] ZOI
   - [x] Update structure type table based on the structure type survey.

**Comment by Jdgilby** [comment]
@nick4rivers @joewheaton @KellyMWhitehead [Heres](https://youtu.be/zQn5YEvhnBI) a video addressing modifications to design and as built forms. Please correct anything I might have been wrong about, I think I got everything from our conversation Friday though.

**Comment by joewheaton** [comment]
Sorry @KellyMWhitehead. I added #265, which was in response to @Jdgilby email. I actually forgot about this ticket you started.
