### ISSUE TITLE
Importing Metrics Tasks

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/QRiS#426]
Ticket to keep track of tasks related to metric definition resources syncing

<img src="https://docs.google.com/drawings/d/e/2PACX-1vTZXapKE3fqD5m8zA_9D3yDEogRbDAMVJWwv4_rKwNAeQyvnLVowUTmBd5U7KCgIlvJQpaAh1TLjSAu/pub?w=1935&amp;h=1077">

## Tasks
- [x] Add Version column to metrics table in gpkg. Make this a unique key with machine_code.
- [x] Add to Version key/value to metric definition json schema and existing json files
- [x] UI updates to support Metric Versions
- [x] GP updates to support metric versions
- [x] Add code/sql snippets to support the edge cases below
- [x] @MattReimer to hook up RSXML/resources syncing of metric definition files
- [x] @KellyMWhitehead update and provide json schema validation script
- [x] script to detect definition changes
- [x] Script to facilitate import logic.

## Questions and Guidelines
- General Metric Maintenance
  - What happens when a user deletes a metric (i.e. in the settings form)? Are the values deleted (cascade delete in database)?
  - What happens if a user trys to update an existing metric? Rejected if same machine_code and version.
- What constitutes a new metric vs an updated metric. This has important implications as to downstream behavior. 
  - Updated is specified by same machine_name but new version (integer). 
  - Because this is a new row in the metric table, qris thinks this is just a new metric. It would be nice to have ui:
    - Label same machine code metrics with version 1, version 2, etc. in display text
    - Offer a way of hiding or deleting old versions of metrics.
- How is the user notified if new and/or updated metrics exist? (i.e. different than what exists in the project)
  - New metrics are loaded into qris when user opens a project.
  - But we also don't want this to be hidden away.
  - Automated vs user-initiated update
- What happens when a metric definition (json) file is updated?
  - Add metric to project as a new version?
  - Keep old metric (definitions)? Keep old values?
  - UI: how to display multiple versions of a metric
  - Do we want to want to copy over the manual values for a previous version?
  - Do we keep old versions in the RSXML library?
- Protocols
  - The concept of a protocol is a little murky right now, but how will we associate specific metrics with a protocol?
  - Do we need to add a key/value to metric definition, or kick this down to protocol definition?
  
## Edge Cases and Testing
- Metric is 
 - Added
   - What if the metric already exists 
 - Updated
   - What if metric value exists
 - Deleted
   - What if metric value exists

**Comment by KellyMWhitehead** [comment]
Metrics importing in version 0.3.24 and updating in 0.3.25
